image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get -v -t -d ./...
  # - init: sudo go get -u github.com/golang/dep/cmd/dep
  #   command: dep ensure
  - init: sudo go get -u github.com/golang/protobuf/protoc-gen-go
  - init: sudo go get github.com/infobloxopen/protoc-gen-gorm
