image:
  file: .gitpod.Dockerfile

tasks:
  - init: go get -u github.com/golang/dep/cmd/dep && dep ensure && go get -u github.com/golang/protobuf/protoc-gen-go && go get github.com/infobloxopen/protoc-gen-gorm
